#ifndef TOKEN_FILE_HPP_
#define TOKEN_FILE_HPP_

#define TOKEN_COMM_LOGIN_U2S          "lo"
/*
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S
#define TOKEN_COMM_LOGIN_U2S*/


#endif//TOKEN_FILE_HPP_